// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqNvi2QfEqCpvH36-FyxwTCJ5H8RFXH3M',
    appId: '1:638060913773:web:b9faf8c39eb80bfe768b64',
    messagingSenderId: '638060913773',
    projectId: 'rlfirebase-9fe7e',
    authDomain: 'rlfirebase-9fe7e.firebaseapp.com',
    storageBucket: 'rlfirebase-9fe7e.appspot.com',
    measurementId: 'G-KCN3LQJ1T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb2cE26t0gynwt9nqgSQ1IDazgON5vNmI',
    appId: '1:638060913773:android:34d57aa2c021c4b2768b64',
    messagingSenderId: '638060913773',
    projectId: 'rlfirebase-9fe7e',
    storageBucket: 'rlfirebase-9fe7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwsicB3KfMSgLlG7BY2bGZHvNfBLXk220',
    appId: '1:638060913773:ios:a4fd08c87415729e768b64',
    messagingSenderId: '638060913773',
    projectId: 'rlfirebase-9fe7e',
    storageBucket: 'rlfirebase-9fe7e.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwsicB3KfMSgLlG7BY2bGZHvNfBLXk220',
    appId: '1:638060913773:ios:a4fd08c87415729e768b64',
    messagingSenderId: '638060913773',
    projectId: 'rlfirebase-9fe7e',
    storageBucket: 'rlfirebase-9fe7e.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqNvi2QfEqCpvH36-FyxwTCJ5H8RFXH3M',
    appId: '1:638060913773:web:1410da3f0497d43d768b64',
    messagingSenderId: '638060913773',
    projectId: 'rlfirebase-9fe7e',
    authDomain: 'rlfirebase-9fe7e.firebaseapp.com',
    storageBucket: 'rlfirebase-9fe7e.appspot.com',
    measurementId: 'G-NME74KKJ3J',
  );
}
